### ISSUE TITLE
sort data in topic by partition and date  

### ISSUE THREAD

**Issue by raschidb** [tchiotludo/kafkahq#125]
When you explore a topic and sort the data by date, the second field is done by partition and not by offset. it  should be better to sort by offset (to see the newer messages)

**Comment by tchiotludo** [comment]
It's an impossible behavior.
Kafka partition is independent and Kafka api don't let us the control on give me the last message first for a whole topic. 
The only way to deal with this case will be to fetch the whole partition on client side and to sort after.
But I don't want to do it since the performance will be poor (and right now sort by newest is already more slow than sorting by oldest due to Kafka API)

**Comment by tchiotludo** [comment]
Fell free the reopen issue If you have any idea :)

**Comment by raschidb** [comment]
Je verrai avec une de nos équipe de dev s’ils ont une idée. 

En tout cas Merci pour la réponse rapide.
