### ISSUE TITLE
Schema Registry update is accessible when running with read-only configuration.

### ISSUE THREAD

**Issue by Expo33** [tchiotludo/kafkahq#128]
hi M. Dehon,  we're running V 0.7 with read-only config for business users.
Our application.yml config:
  # Auth & Roles (optional)
  security:
    default-roles: # Roles available for all the user even unlogged user
    - node/read
    - topic/read
    - topic/data/read
    - group/read
    - registry/read

It was reported by a user that Update is available in Schema Registry.  We confirmed that's true.  Compatibility Level can be changed. Also, message body can be changed, with the update creating a new version.  The new version cannot be deleted without first restoring registry/version/delete .
I didn't notice other issues discussing this aspect.  Looking for your thoughts.

thanks!

**Comment by tchiotludo** [comment]
As I see the button is present (that is fixed on dev) but the user can really update the schema.

Tell me if there is another thing I don't see.

Thanks for the report

**Comment by Expo33** [comment]
Thanks again for the good work.
Question: what's the best way to get a V 0.7 kafkahq.jar that includes the fix?
And.. are you planning for a commercial version?
Salut

**Comment by tchiotludo** [comment]
For now, the fix is only on dev branch !

Just a question, why do you want to stay on 0.7 version ?

For commercial version, I don't have time for now to think about to be honest. 
Maybe you can explain me a little bit more what you kind of commercial version do you need ?

**Comment by Expo33** [comment]
We ran V 0.9 for a time, but users complained of the high rate of timeouts, and the pagination.  When we went back to V 0.7 they were pleased.
I work for a Telecom  in Canada. We’re bringing significant volumes of transaction messaging into Kafka.  There’s a potential user base for KafkaHQ.
We have history of paying for suitable software.  KafkaHQ might be in that category, in future .

Curtis

**Comment by cg-nz** [comment]
I'd also like to second this - we went back to 0.7 for the timeouts too.
I work for large utility company who would also pay for suitable software, such as this. Just food for thought! Thanks very much again.

Cheers
cg

**Comment by tchiotludo** [comment]
Thanks for the feedback !

@cg-nz & @expo33, do you work both for the same company ?
Seems that KafkaHQ may have a largest user based on Canada that I know 😁

Ok remember for this issue and I don't catch that users went back to old version & stick it since pagination is here.
To be honest, performance is for now my main issue and I try some optimization on my free (limited) time.

Maybe it can be nice to have a discussion by email on what is your usage of KafkaHQ: concurrent users, installation (docker, k8, hardware, ...), usage, criticity,...
There is always a solution, just need to talk about the possible one 😁

> tchiot.ludo@gmail.com

Thanks for all

**Comment by tchiotludo** [comment]
Hey @here ! 
New release of version 0.10.0 include the fix and also an option that could help on performance : https://github.com/tchiotludo/kafkahq#pagination especially this option `kafkahq.pagination.threads`. 

Maybe It can help to go to last version ? 

Tell me what is your feeling.

**Comment by tchiotludo** [comment]
hey @cg-nz & @Expo33, we should try the last dev version. 
I've reverted some change on pagination and this version must be same than 0.7.0, maybe more speedy than this old version.
I completely changed the pagination on dev version to remove multi thread and will be more near than before the pagination, but will be more optimize since pagination reduce the number of fetch on kafka api. 
Feel free to tell me what is your feeling on this one, thanks

**Comment by tchiotludo** [comment]
release 0.11.0 include this improvement if you to see it :)
