### ISSUE TITLE
How to enable verbose logging with HELM deployment

### ISSUE THREAD

**Issue by JakePDaniel** [tchiotludo/kafkahq#188]
I am trying to enable LDAP auth to my service, deployed using HELM.  While trying to debug my ldap configuration values I am trying to look at the debug log level as nothing is showing in my container logs. Is it possible to turn on verbose logging?

**Comment by tchiotludo** [comment]
The best option since you are on k8s is to connect to kafkahq pods and run this command : 

```bash
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:8080/loggers/io.micronaut.configuration.security
```
It will increase the log level for the current session on the micronaut part that handle ldap auth 

You can also add an env var `JAVA_OPTS` with `-Dlogback.configurationFile=/path/to/config.xml` and inject a custom logback.xml in your pods if you need this be permanent (not for current session) 

Hope it will help

**Comment by JakePDaniel** [comment]
Thank you for the quick response. I was able to get LDAP working. For LDAP if you want to enable anonymous auth to your LDAP server you can pass             
managerDn: ''
managerPassword: ''

Something to add to the documentation possibly as I couldn't find that anywhere.

**Comment by tchiotludo** [comment]
reopen to think about documentation
