### ISSUE TITLE
How can I delete specific/all messages on a topic?

### ISSUE THREAD

**Issue by ashwinigowda91** [tchiotludo/kafkahq#223]
I did read the documentation which mentions the feature to delete messages on the topic. I am just wondering if there is a way to delete specific messages on a topic? I do have a user who is able to perform the below operations:
topic/data/read, topic/data/insert and topic/data/delete
But I do not see an option to delete messages when I view the topic in the dashboard. Am I missing something?

**Comment by tchiotludo** [comment]
The topic need to be compacted, in this case, the delete button will be available. 
In other case, Kafka don't allow to delete topic data.

**Comment by ashwinigowda91** [comment]
Thanks for the response. It does work for me. I see that a null value gets inserted for the record that gets deleted. This looks like a soft delete of the record. I am using Kafka Connect as a consumer and it actually picks up the null value records(deleted). It would be ideal to not have a soft-delete. Is that possible ?

**Comment by ashwinigowda91** [comment]
One of the things I have been able to do is to skip the null value records by updating the offset(which is a great feature!)

**Comment by tchiotludo** [comment]
The insertion of null value is the way Kafka works.
You have to insert the null values and Kafka will pickup all null values on compaction.
The compaction is a broker or topic configuration that you can change in order to speed up : https://github.com/tchiotludo/kafkahq/blob/c09be06d175104f4a3509d2a0566f7be781406d8/src/test/java/org/kafkahq/KafkaTestCluster.java#L89
But there is no guarantee on that and Kafka consumer must be tolerant and must handle null values.
