### ISSUE TITLE
Website basic auth

### ISSUE THREAD

**Issue by syepes** [tchiotludo/kafkahq#35]
Hello,
Is there currently a way of enabling some sort of basic authentication on the web server?
I would like to have some minimal security without going the hole SSL route.

**Comment by tchiotludo** [comment]
I'm working right now on basic auth authentification for the next release with some role based access control.
Since I rely on micronaut, maybe more advance authentification will be possible (LDAP for example) in a another future release.

In the meantime, micronaut seems to have a built-in [ssl client authentification](https://docs.micronaut.io/latest/guide/configurationreference.html#io.micronaut.http.ssl.ServerSslConfiguration) but I never try it.
Other solution will be a simple reverse proxy with authentification. 
But I hope to release the basic auth before the end of month.

**Comment by tchiotludo** [comment]
Just release [0.5.0](https://github.com/tchiotludo/kafkahq/releases/tag/0.5.0) with basic auth !
