### ISSUE TITLE
Update README.md with SASL example

### ISSUE THREAD

**Issue by baluchicken** [tchiotludo/kafkahq#37]
The documentation says that Kafkahq supports connecting to a Kafka cluster where SASL is enabled. 
Can you please provide an example or extend the documentation how to configure the UI to access a cluster using SASL.

**Comment by tchiotludo** [comment]
I never really do be honest ! 
I'm sure that it works since Kafka Java client support it and it must be the same than describe [here](https://docs.confluent.io/current/kafka/authentication_sasl/index.html).

As soon as I have time, I'll try to follow this [demo](https://docs.confluent.io/current/tutorials/cp-demo/docs/index.html) to have a sasl cluster in order to add configuration to README.

If anyone have the solution, PR are welcome :pray:

**Comment by baluchicken** [comment]
Thanks for the quick response, I just made it work. I will submit a PR soon with the details.

**Comment by tchiotludo** [comment]
glad to hear it !!! 
Thanks :+1:
