### ISSUE TITLE
Topic size in compacted topics

### ISSUE THREAD

**Issue by ljupcovangelski** [tchiotludo/kafkahq#66]
Kafkahq is a wonderful tool, but we recently noticed that for topics which are compacted, the `size of the topic` (2nd column on the Topics page) is actually the sum of all current offsets, for all partitions and not the number of messages which are actually in the topic.

I'm not sure if this is how it should be or is it a bug.

We have topic with 64 partitions, which is compacted and has `1,114,892` messages, while kafkahq reports that it has `13,699,338`.

When we list the messages in kafkahq, we can also view the gaps between the offsets, because of the messages which are compacted.

**Comment by tchiotludo** [comment]
Thanks for the feedback, glad to see you enjoy it :smile: 

for the compacted topic, I can't really know the size of the topic as I know. 
The Kafka Api only return start and end offset, that I sum. 
I keep the value displayed just to know when the size is increasing, but the value is not relevant. 
I think i will only add the `≈` for compacted topic, since for not compacted topic the size is exact.

As I know, there is no way to have the real size of a topic but If anyone have a wonderful idea help, it will be really appreciate. 

Just for information, how do you know that you have `1,114,892` exactly ?

**Comment by ljupcovangelski** [comment]
Thanks for the reply. We just consumed the messages, but we need to make sure first that there is no producer writing to the topic. I couldn't find any other correct way to determine the number of messages in the topic, apart from:
- stopping producers
- consuming the whole topic
- counting the messages

We will think about a possible solution for this and hopefully we can contribute to this great project, with this feature!

Just one more question. Is the `Weight` calculated on behalf of the `Size` parameter or is it completely separate?

**Comment by tchiotludo** [comment]
Hope you have a magic bottle for the size. 😁

The weight is based on log dir size directly from Kafka. So this value is relevant

**Comment by tchiotludo** [comment]
Close as no solution as I know, feel free to reopen with solution :smile:
